import { motion } from 'framer-motion';
import { Brain, X, Sparkles, MessageSquareQuote } from 'lucide-react';

interface AiSummaryModalProps {
    isOpen: boolean;
    onClose: () => void;
    isLoading: boolean;
    insight: string | null;
}

export function AiSummaryModal({ isOpen, onClose, isLoading, insight }: AiSummaryModalProps) {
    if (!isOpen) return null;

    return (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
            {/* Backdrop */}
            <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                onClick={onClose}
                className="absolute inset-0 bg-black/80 backdrop-blur-sm"
            />

            {/* Modal Content */}
            <motion.div
                initial={{ opacity: 0, scale: 0.95, y: 20 }}
                animate={{ opacity: 1, scale: 1, y: 0 }}
                exit={{ opacity: 0, scale: 0.95, y: 20 }}
                className="relative z-10 w-full max-w-2xl bg-[#0F0F13] border border-white/10 rounded-2xl overflow-hidden shadow-2xl"
            >
                {/* Header */}
                <div className="flex items-center justify-between p-6 border-b border-white/5 bg-gradient-to-r from-purple-500/10 to-transparent">
                    <div className="flex items-center gap-3">
                        <div className="p-2 bg-purple-500/20 rounded-lg text-purple-400">
                            <Brain size={24} />
                        </div>
                        <div>
                            <h2 className="text-xl font-bold text-white">Spectre AI Analizi</h2>
                            <p className="text-xs text-gray-400">Verilerinizi inceledim, işte bugünün özeti.</p>
                        </div>
                    </div>
                    <button onClick={onClose} className="p-2 hover:bg-white/10 rounded-full text-gray-400 hover:text-white transition-colors">
                        <X size={20} />
                    </button>
                </div>

                {/* Body */}
                <div className="p-8 min-h-[200px] flex items-center justify-center">
                    {isLoading ? (
                        <div className="flex flex-col items-center gap-4 text-center">
                            <div className="relative">
                                <div className="absolute inset-0 bg-purple-500 blur-xl opacity-20 animate-pulse" />
                                <Brain size={64} className="text-purple-400 animate-pulse relative z-10" />
                            </div>
                            <div className="space-y-1">
                                <h3 className="text-lg font-medium text-white">Analiz Ediliyor...</h3>
                                <p className="text-sm text-gray-500">Milyonlarca veri noktasını tarıyorum 🕵️‍♂️</p>
                            </div>
                        </div>
                    ) : (
                        <div className="w-full">
                            {insight ? (
                                <div className="relative">
                                    <MessageSquareQuote size={48} className="absolute -top-6 -left-4 text-purple-500/10 transform -scale-x-100" />
                                    <div className="text-lg md:text-xl text-gray-200 leading-relaxed font-light pl-6 border-l-2 border-purple-500/30 italic">
                                        "{insight}"
                                    </div>
                                    <div className="mt-8 flex justify-end">
                                        <span className="text-xs font-mono text-purple-400 flex items-center gap-1 bg-purple-500/10 px-3 py-1 rounded-full">
                                            <Sparkles size={12} />
                                            Generated by Spectre AI
                                        </span>
                                    </div>
                                </div>
                            ) : (
                                <div className="text-center text-gray-500">
                                    <p>Bir hata oluştu veya analiz oluşturulamadı.</p>
                                    <button onClick={onClose} className="mt-4 text-sm text-purple-400 hover:underline">Kapat</button>
                                </div>
                            )}
                        </div>
                    )}
                </div>
            </motion.div>
        </div>
    );
}
