ALTER TABLE goals ADD COLUMN page_title VARCHAR(255) DEFAULT NULL AFTER url;
ALTER TABLE events ADD COLUMN page_title VARCHAR(255) DEFAULT NULL AFTER url;
ALTER TABLE heatmap_data ADD COLUMN page_title VARCHAR(255) DEFAULT NULL AFTER url;
